name: web_scraper
description: A simple web scraper to scrape HTML tags and their attributes to cast them into Lists and Maps for dart and flutter.
version: 0.1.4
homepage: https://github.com/tusharojha/web_scraper

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  html:
  http:

dev_dependencies:
  test:
  pedantic:
